/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UT7.TA4;

import java.util.Objects;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Nicolas
 */
public class Panel extends javax.swing.JFrame {
    public final String[] metodos={"Insercion Directa","Array1","Burbuja","Quicksort","Heapsort", "Seleccion Directa","Array2"};

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        for(String m:metodos){
            jComboBoxMetodo.addItem(m);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxMetodo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTamanio = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelAscendente = new javax.swing.JLabel();
        jLabelDescendente = new javax.swing.JLabel();
        jLabelAleatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxMetodo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBoxMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMetodoActionPerformed(evt);
            }
        });

        jLabel1.setText("MÉTODO");

        jLabel2.setText("TAMAÑO CONJUNTOS");

        jTextFieldTamanio.setText("0");
        jTextFieldTamanio.setHighlighter(null);
        jTextFieldTamanio.setInheritsPopupMenu(true);
        jTextFieldTamanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTamanioActionPerformed(evt);
            }
        });

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jLabel3.setText("Ascendente:");

        jLabel4.setText("Descendente:");

        jLabel5.setText("Aleatorio:");

        jLabel6.setText("TIEMPOS");

        jLabelAscendente.setText("0");

        jLabelDescendente.setText("0");

        jLabelAleatorio.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 36, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldTamanio)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonOK))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAleatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDescendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAscendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOK))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelAscendente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelDescendente))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelAleatorio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTamanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTamanioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTamanioActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        int metodo=jComboBoxMetodo.getSelectedIndex()+1;
        System.out.println(metodo);
        try{
            int tamanio=Integer.parseInt(jTextFieldTamanio.getText());
            System.out.println(tamanio);
            TClasificador clasif = new TClasificador();
            GeneradorDatosGenericos gdg = new GeneradorDatosGenericos(tamanio);
            int[] vectorOriginal = gdg.generarDatosAleatorios();

            long t1 = System.nanoTime();
            long total = 0;
            int cantLlamadas = 0;
            long tiempoResolucion = (long) Math.pow(10, 9);

            while (total < tiempoResolucion){
                cantLlamadas++;
                int[] datosCopia = vectorOriginal;
                clasif.clasificar(datosCopia, metodo, true);
                long t2 = System.nanoTime();
                total = t2 - t1;
            }

            long tiempoMedioAB = total/cantLlamadas;
            vectorOriginal = gdg.generarDatosAleatorios();

            t1 = System.nanoTime();
            total = 0;
            cantLlamadas = 0;

            while (total < tiempoResolucion){
                cantLlamadas++;
                int[] datosCopia = vectorOriginal;
                clasif.clasificar(datosCopia, metodo, false);
                long t2 = System.nanoTime();
                total = t2 - t1;
            }

            long tiempoMedioC = total/cantLlamadas;
            long tiempoMedioAlgoritmo = tiempoMedioAB - tiempoMedioC;
            jLabelAleatorio.setText(Objects.toString(tiempoMedioAlgoritmo));

            int[] vectorOriginalA = gdg.generarDatosAscendentes();

            t1 = System.nanoTime();
            total = 0;
            cantLlamadas = 0;
            tiempoResolucion = (long) Math.pow(10, 9);

            while (total < tiempoResolucion){
                cantLlamadas++;
                int[] datosCopia = vectorOriginalA;
                clasif.clasificar(datosCopia, metodo, true);
                long t2 = System.nanoTime();
                total = t2 - t1;
            }

            tiempoMedioAB = total/cantLlamadas;
            vectorOriginalA = gdg.generarDatosAscendentes();

            t1 = System.nanoTime();
            total = 0;
            cantLlamadas = 0;

            while (total < tiempoResolucion){
                cantLlamadas++;
                int[] datosCopia = vectorOriginalA;
                clasif.clasificar(datosCopia, metodo, false);
                long t2 = System.nanoTime();
                total = t2 - t1;
            }

            tiempoMedioC = total/cantLlamadas;
            tiempoMedioAlgoritmo = tiempoMedioAB - tiempoMedioC;

            jLabelAscendente.setText(Objects.toString(tiempoMedioAlgoritmo));


            int[] vectorOriginalD = gdg.generarDatosDescendentes();

            t1 = System.nanoTime();
            total = 0;
            cantLlamadas = 0;
            tiempoResolucion = (long) Math.pow(10, 9);

            while (total < tiempoResolucion){
                cantLlamadas++;
                int[] datosCopia = vectorOriginalD;
                clasif.clasificar(datosCopia, metodo, true);
                long t2 = System.nanoTime();
                total = t2 - t1;
            }

            tiempoMedioAB = total/cantLlamadas;
            vectorOriginalD = gdg.generarDatosDescendentes();

            t1 = System.nanoTime();
            total = 0;
            cantLlamadas = 0;

            while (total < tiempoResolucion){
                cantLlamadas++;
                int[] datosCopia = vectorOriginalD;
                clasif.clasificar(datosCopia, metodo, false);
                long t2 = System.nanoTime();
                total = t2 - t1;
            }

            tiempoMedioC = total/cantLlamadas;
            tiempoMedioAlgoritmo = tiempoMedioAB - tiempoMedioC;
                

            jLabelDescendente.setText(Objects.toString(tiempoMedioAlgoritmo));
        }catch(NumberFormatException e){
            showMessageDialog(null,"No se ingresó un tamaño válido");
        }
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jComboBoxMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMetodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox<String> jComboBoxMetodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAleatorio;
    private javax.swing.JLabel jLabelAscendente;
    private javax.swing.JLabel jLabelDescendente;
    private javax.swing.JTextField jTextFieldTamanio;
    // End of variables declaration//GEN-END:variables
}
